"""
Tests for ConsensusCore - the main facade for consensus operations.

This test suite verifies the ConsensusCore class which provides the primary
interface for creating and managing consensus instances.
"""

from typing import Any, Type
from unittest.mock import AsyncMock, MagicMock

import pytest
from pydantic import BaseModel, Field

from blockether_catalyst.consensus.Consensus import Consensus
from blockether_catalyst.consensus.ConsensusCore import ConsensusCore
from blockether_catalyst.consensus.ConsensusTypes import (
    ConsensusSettings,
    ModelConfiguration,
)
from blockether_catalyst.consensus.VotingComparison import (
    BaseModelWithReasoning,
    ComparisonStrategy,
    VotingField,
)
from blockether_catalyst.utils.TypedCalls import ArityOneTypedCall


class ConsensusTestResponse(BaseModelWithReasoning):
    """Test response model that extends BaseModelWithReasoning."""

    answer: str = VotingField(
        description="The answer",
        comparison=ComparisonStrategy.EXACT,  # Exact match for testing
    )
    confidence: float = VotingField(
        default=0.9,
        description="Confidence level",
        comparison=ComparisonStrategy.RANGE,
        tolerance=0.1,  # Allow 10% variance
    )


class MockTypedCall(ArityOneTypedCall[str, ConsensusTestResponse]):
    """Mock typed call for testing."""

    def __init__(self, answer: str = "deterministic_answer", confidence: float = 0.95) -> None:
        """Initialize mock with deterministic response."""
        self._answer = answer
        self._confidence = confidence

    async def call(self, x: str) -> ConsensusTestResponse:
        """Return deterministic response."""
        return ConsensusTestResponse(
            answer=self._answer,
            confidence=self._confidence,
            reasoning=f"Deterministic response: {self._answer} with confidence {self._confidence} for input: {x}. This response is generated by a deterministic mock model that always returns the same predetermined values for consistent testing. The reasoning includes detailed explanation of the mock behavior and validation of input processing to meet minimum character requirements for proper consensus validation.",
        )


class TestConsensusCore:
    """Test suite for ConsensusCore facade."""

    @pytest.fixture
    def core(self) -> Any:
        """Create ConsensusCore instance."""
        return ConsensusCore()

    @pytest.fixture
    def mock_executor(self) -> Any:
        """Create mock typed call."""
        return MockTypedCall(answer="test_answer", confidence=0.90)

    @pytest.fixture
    def test_initialization(self, core: Any) -> None:
        """Test ConsensusCore initialization."""
        assert isinstance(core, ConsensusCore)

    def test_consensus_default(self, core: Any, mock_executor: Any) -> None:
        """Test creating Consensus with defaults."""
        models = [
            core.model(
                id="test-model-1",
                executor=mock_executor,
                perspective="As test model 1",
            ),
            core.model(
                id="test-model-2",
                executor=mock_executor,
                perspective="As test model 2",
            ),
            core.model(
                id="test-model-3",
                executor=mock_executor,
                perspective="As test model 3",
            ),
        ]
        judge = mock_executor  # Use same executor as judge
        consensus = core.consensus(models=models, judge=judge)

        assert consensus.__class__.__name__ == "Consensus"
        assert consensus.settings.max_rounds == 5
        assert consensus.settings.threshold == 0.5
        # First round threshold is auto-adjusted for 3 models (max is 0.667)
        assert consensus.settings.first_round_threshold < 0.667
        assert consensus.settings.max_concurrent_calls == 10

    def test_consensus_with_settings(self, core: Any, mock_executor: Any) -> None:
        """Test creating Consensus with custom settings."""
        models = [
            core.model(
                id="test-model-1",
                executor=mock_executor,
                perspective="As test model 1",
            ),
            core.model(
                id="test-model-2",
                executor=mock_executor,
                perspective="As test model 2",
            ),
            core.model(
                id="test-model-3",
                executor=mock_executor,
                perspective="As test model 3",
            ),
        ]
        settings = ConsensusSettings(
            max_concurrent_calls=5,
        )

        judge = mock_executor  # Use same executor as judge
        consensus = core.consensus(models=models, judge=judge, settings=settings)

        assert consensus.__class__.__name__ == "Consensus"
        assert consensus.settings.max_concurrent_calls == 5
        assert consensus.settings.max_rounds == 5
        assert consensus.settings.threshold == 0.5
        # First round threshold is auto-adjusted for 3 models (max is 0.667)
        assert consensus.settings.first_round_threshold < 0.667

    def test_configuration(self, core: Any, mock_executor: Any) -> None:
        """Test creating model configuration."""
        config = core.model(
            id="test-model",
            executor=mock_executor,
            perspective="As a test model",
            weight_multiplier=0.8,
        )

        assert "ModelConfiguration" in config.__class__.__name__
        assert config.id == "test-model"
        assert config.executor == mock_executor
        assert config.weight_multiplier == 0.8
        assert config.perspective == "As a test model"

    def test_configuration_with_weight(self, core: Any, mock_executor: Any) -> None:
        """Test creating model configuration with custom weight."""
        config = core.model(
            id="expert-model",
            executor=mock_executor,
            perspective="As an expert",
            weight_multiplier=2.0,
        )

        assert config.id == "expert-model"
        assert config.weight_multiplier == 2.0

    def test_create_consensus_request_removed(self, core: Any, mock_executor: Any) -> None:
        """Test that consensus request creation was simplified."""
        models = [core.model(id=f"model-{i}", executor=mock_executor, perspective=f"As model {i}") for i in range(3)]

        # ConsensusRequest was removed - consensus is now directly created
        from blockether_catalyst.consensus.ConsensusTypes import ConsensusSettings

        settings = ConsensusSettings(max_rounds=3)
        judge = mock_executor  # Use same executor as judge
        consensus = core.consensus(models=models, judge=judge, settings=settings)

        assert consensus.__class__.__name__ == "Consensus"
        assert len(consensus.models) == 3
        assert consensus.models[0].id == "model-0"
        assert consensus.models[1].id == "model-1"
        assert consensus.models[2].id == "model-2"
        assert consensus.settings.max_rounds == 3

    @pytest.mark.anyio
    async def test_full_consensus_workflow(self, core: Any) -> None:
        """Test complete consensus workflow using ConsensusCore with deterministic models."""
        # Create deterministic models that all return the same answer for consensus
        deterministic_executor = MockTypedCall(answer="life_meaning_42", confidence=0.98)
        judge_executor = MockTypedCall(answer="life_meaning_42", confidence=0.99)

        models = [
            core.model(
                id=f"model-{i}",
                executor=deterministic_executor,
                perspective=f"As model {i}",
                weight_multiplier=1.0 - (i * 0.1),
            )
            for i in range(3)
        ]

        # Create and execute consensus directly
        from blockether_catalyst.consensus.ConsensusTypes import ConsensusSettings

        settings = ConsensusSettings(max_rounds=3)
        consensus = core.consensus(models=models, judge=judge_executor, settings=settings)
        result = await consensus.call("What is the meaning of life?")

        # Strong exact assertions
        assert result.consensus_achieved is True
        assert result.total_rounds == 1
        assert len(result.participating_models) == 3
        assert result.final_response.__class__.__name__ == "ConsensusTestResponse"
        assert result.final_response.answer == "life_meaning_42"
        assert result.final_response.confidence == 0.98

    def test_static_methods_are_static(self) -> None:
        """Test that static methods work without instance."""
        # Create mock typed call
        mock_call = MockTypedCall(answer="static_test_answer", confidence=0.96)

        # Test static method without instance
        config1 = ConsensusCore.model(id="static-test-1", executor=mock_call, perspective="As static test 1")
        config2 = ConsensusCore.model(id="static-test-2", executor=mock_call, perspective="As static test 2")
        config3 = ConsensusCore.model(id="static-test-3", executor=mock_call, perspective="As static test 3")
        assert config1.id == "static-test-1"
        assert config1.perspective == "As static test 1"
        assert config1.weight_multiplier == 1.0

        consensus = ConsensusCore.consensus(models=[config1, config2, config3], judge=mock_call)
        assert consensus.__class__.__name__ == "Consensus"
        assert len(consensus.models) == 3
        assert consensus.models[0].id == "static-test-1"
        assert consensus.models[1].id == "static-test-2"
        assert consensus.models[2].id == "static-test-3"

    def test_type_annotations(self, core: Any) -> None:
        """Test that all methods have proper type annotations."""
        # This test verifies that the methods are properly typed
        # by checking their signatures
        import inspect

        # Check consensus
        sig = inspect.signature(core.consensus)
        # The return type is actually Consensus[T] (generic), not just Consensus
        assert "Consensus" in str(sig.return_annotation)

        # Check configuration
        sig = inspect.signature(core.model)
        # The return type is actually ModelConfiguration[T] (generic), not just ModelConfiguration
        assert "ModelConfiguration" in str(sig.return_annotation)

        # create_consensus_request was removed - check that it doesn't exist
        assert not hasattr(core, "create_consensus_request")
